name: FG-BERT
channels:
  - rdkit
  - openbabel
  - anaconda
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - blas=1.0=openblas
  - bottleneck=1.3.5=py37h7deecbd_0
  - brotli=1.0.9=h5eee18b_7
  - brotli-bin=1.0.9=h5eee18b_7
  - bzip2=1.0.8=h7b6447c_0
  - ca-certificates=2022.07.19=h06a4308_0
  - cairo=1.14.12=h8948797_3
  - certifi=2022.6.15=py37h06a4308_0
  - cudatoolkit=10.1.243=h6bb024c_0
  - cudnn=7.6.5=cuda10.1_0
  - cycler=0.11.0=pyhd3eb1b0_0
  - daal4py=2021.5.0=py37h78b71dc_0
  - dal=2021.5.1=h06a4308_803
  - dbus=1.13.18=hb2f20db_0
  - expat=2.4.4=h295c915_0
  - fontconfig=2.13.1=h6c09931_0
  - freetype=2.11.0=h70c0345_0
  - giflib=5.2.1=h7b6447c_0
  - glib=2.63.1=h5a9c865_0
  - gst-plugins-base=1.14.0=hbbd80ab_1
  - gstreamer=1.14.0=hb453b48_1
  - icu=58.2=he6710b0_3
  - intel-openmp=2021.4.0=h06a4308_3561
  - joblib=1.1.0=pyhd3eb1b0_0
  - jpeg=9e=h7f8727e_0
  - lcms2=2.12=h3be6417_0
  - libboost=1.67.0=h46d08c1_4
  - libbrotlicommon=1.0.9=h5eee18b_7
  - libbrotlidec=1.0.9=h5eee18b_7
  - libbrotlienc=1.0.9=h5eee18b_7
  - libedit=3.1.20210910=h7f8727e_0
  - libffi=3.2.1=hf484d3e_1007
  - libgcc-ng=11.2.0=h1234567_1
  - libgfortran-ng=7.5.0=ha8ba4b0_17
  - libgfortran4=7.5.0=ha8ba4b0_17
  - libgomp=11.2.0=h1234567_1
  - libopenblas=0.3.18=hf726d26_0
  - libpng=1.6.37=hbc83047_0
  - libstdcxx-ng=11.2.0=h1234567_1
  - libtiff=4.2.0=h2818925_1
  - libuuid=1.0.3=h7f8727e_2
  - libwebp=1.2.2=h55f646e_0
  - libwebp-base=1.2.2=h7f8727e_0
  - libxcb=1.15=h7f8727e_0
  - libxml2=2.9.14=h74e7548_0
  - lz4-c=1.9.3=h295c915_1
  - matplotlib-base=3.4.3=py37hbbc1b5f_0
  - mkl=2021.4.0=h06a4308_640
  - mkl-service=2.4.0=py37h7f8727e_0
  - mpi=1.0=mpich
  - mpich=3.3.2=hc856adb_0
  - munkres=1.1.4=py_0
  - ncurses=6.3=h5eee18b_3
  - numpy-base=1.18.5=py37h2f8d375_0
  - openbabel=2.4.1=py37_6
  - openssl=1.0.2u=h7b6447c_0
  - packaging=21.3=pyhd3eb1b0_0
  - pandas=1.1.0=py37he6710b0_0
  - pcre=8.45=h295c915_0
  - pillow=9.2.0=py37hace64e9_1
  - pip=22.1.2=py37h06a4308_0
  - pixman=0.40.0=h7f8727e_1
  - py-boost=1.67.0=py37h04863e7_4
  - pyparsing=3.0.4=pyhd3eb1b0_0
  - pyqt=5.9.2=py37h05f1152_2
  - python=3.7.0=h6e4f718_3
  - python-dateutil=2.8.2=pyhd3eb1b0_0
  - pytz=2022.1=py37h06a4308_0
  - qt=5.9.6=h8703b6f_2
  - rdkit=2020.03.2.0=py37hc20afe1_1
  - readline=7.0=h7b6447c_5
  - scikit-learn=1.0.2=py37h51133e4_1
  - scikit-learn-intelex=2021.5.0=py37h06a4308_0
  - setuptools=61.2.0=py37h06a4308_0
  - sip=4.19.8=py37hf484d3e_0
  - six=1.16.0=pyhd3eb1b0_1
  - sqlite=3.33.0=h62c20be_0
  - tbb=2021.5.0=hd09550d_0
  - threadpoolctl=2.2.0=pyh0d69192_0
  - tk=8.6.12=h1ccaba5_0
  - tornado=6.1=py37h27cfd23_0
  - typing_extensions=4.3.0=py37h06a4308_0
  - wheel=0.37.1=pyhd3eb1b0_0
  - xz=5.2.5=h7f8727e_1
  - zlib=1.2.12=h7f8727e_2
  - zstd=1.5.2=ha4553b6_0
  - pip:
    - absl-py==1.2.0
    - astunparse==1.6.3
    - cachetools==5.2.0
    - charset-normalizer==2.1.0
    - cloudpickle==2.1.0
    - fonttools==4.34.4
    - future==0.18.2
    - gast==0.3.3
    - google-auth==2.10.0
    - google-auth-oauthlib==0.4.6
    - google-pasta==0.2.0
    - grpcio==1.47.0
    - h5py==2.10.0
    - hyperopt==0.2.7
    - idna==3.3
    - importlib-metadata==4.12.0
    - keras-preprocessing==1.1.2
    - kiwisolver==1.4.4
    - markdown==3.4.1
    - markupsafe==2.1.1
    - matplotlib==3.5.2
    - networkx==2.6.3
    - numpy==1.18.5
    - oauthlib==3.2.0
    - opt-einsum==3.3.0
    - protobuf==3.19.4
    - py4j==0.10.9.7
    - pyasn1==0.4.8
    - pyasn1-modules==0.2.8
    - requests==2.28.1
    - requests-oauthlib==1.3.1
    - rsa==4.9
    - scipy==1.4.1
    - tensorboard==2.9.1
    - tensorboard-data-server==0.6.1
    - tensorboard-plugin-wit==1.8.1
    - tensorflow==2.3.0
    - tensorflow-estimator==2.3.0
    - tensorflow-gpu==2.3.0
    - termcolor==1.1.0
    - tqdm==4.64.0
    - urllib3==1.26.11
    - werkzeug==2.2.1
    - wrapt==1.14.1
    - zipp==3.8.1
prefix: /share/home/yyzh/anaconda3/envs/FG-BERT
